### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sjlongland** [lettier/ntpclient#1]
Hi,

I just stumbled across your NTP client implementation… and at the moment I've got a need for a nice small NTP client for use in an embedded device (ARM Cortex M3-based) which runs the OpenThread network stack.

I was wondering what the license was for your project, and whether you are happy for us to use your code in a commercial product?  My thinking is that I'll port your C code across to use the OpenThread API and contribute it there (retaining your original copyright of course)… OpenThread is licensed under the 3-clause BSD license.

https://github.com/openthread/openthread

If you could let us know what the licensing is on your client, that would be a big help. :-)

**Comment by lettier** [comment]
Hello and thank you for your interest in my NTP client.

Sure no problem. I have licensed it under BSD 3-Clause License.

Cheers! :+1:

**Comment by sjlongland** [comment]
That's great.  Thanks for your effort on this. :-)
