### ISSUE TITLE
Bug report: socket not closed

### ISSUE THREAD

**Issue by Vxider** [lettier/ntpclient#6]
Hi, Thank you for your awesome work, I found that you have forgot close socket in `main.c`.

**Comment by lettier** [comment]
Hello @Vxider and thank you for opening an issue.

The file descriptor (socket) will be closed by the operating system very shortly after the program reads from the socket. 

If this program were to continue on, having no more need for the socket, then yes we would need to close it or suffer wasting resources.

The purpose of this project is to demonstrate communicating with a NTP server. As such, the code was kept short and accessibly informative. 

:+1:
